# Generated by Django 4.2.27 on 2026-02-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dailyrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecommendation',
            name='recommended_reason',
            field=models.TextField(blank=True, help_text='AI推荐理由', null=True),
        ),
        migrations.AddField(
            model_name='dailyrecommendation',
            name='recommended_video_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dailyrecommendation',
            name='recommended_video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
