# Generated by Django 4.2.27 on 2026-02-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dailyrecommendation_recommended_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='是否暂存（不想学了）'),
        ),
    ]
