# Generated by Django 4.2.27 on 2026-02-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_topic_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicRecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_keyword', models.CharField(db_index=True, max_length=200)),
                ('level', models.CharField(max_length=50)),
                ('video_title', models.CharField(max_length=500)),
                ('video_url', models.URLField(max_length=500)),
                ('reason', models.TextField(help_text='AI推荐理由')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['topic_keyword', 'level'], name='core_topicr_topic_k_52ed47_idx')],
            },
        ),
    ]
